version: '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imdb
    ports:
      - ${PORT:-3306}:3306
    volumes:
      - db_vol:/var/lib/mysql
      - ./mysql/dumps:/dumps
      - ./mysql/conf.d:/etc/mysql/conf.d

volumes:
  db_vol: